#############################################################################
# Makefile for building: ningeProject
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 1? 9 14:12:47 2012
# Project:  ningeProject.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ningeProject.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-core \
		sub-ninge \
		sub-ningePlayer \
		sub-ningeMain \
		sub-ningeGal

core//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) core/ || $(MKDIR) core/ 
	cd core/ && $(QMAKE) /home/ninsun/ningeproject-ninge/core/core.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-core-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) core/ || $(MKDIR) core/ 
	cd core/ && $(QMAKE) /home/ninsun/ningeproject-ninge/core/core.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-core: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE)
sub-core-make_default: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) 
sub-core-make_first: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) first
sub-core-all: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) all
sub-core-clean: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) clean
sub-core-distclean: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) distclean
sub-core-install_subtargets: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) install
sub-core-uninstall_subtargets: core//$(MAKEFILE) FORCE
	cd core/ && $(MAKE) -f $(MAKEFILE) uninstall
ninge//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ninge/ || $(MKDIR) ninge/ 
	cd ninge/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ninge/ninge.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ninge-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ninge/ || $(MKDIR) ninge/ 
	cd ninge/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ninge/ninge.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ninge: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE)
sub-ninge-make_default: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) 
sub-ninge-make_first: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) first
sub-ninge-all: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) all
sub-ninge-clean: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) clean
sub-ninge-distclean: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ninge-install_subtargets: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) install
sub-ninge-uninstall_subtargets: ninge//$(MAKEFILE) FORCE
	cd ninge/ && $(MAKE) -f $(MAKEFILE) uninstall
ningePlayer//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ningePlayer/ || $(MKDIR) ningePlayer/ 
	cd ningePlayer/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningePlayer/ningePlayer.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningePlayer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ningePlayer/ || $(MKDIR) ningePlayer/ 
	cd ningePlayer/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningePlayer/ningePlayer.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningePlayer: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE)
sub-ningePlayer-make_default: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) 
sub-ningePlayer-make_first: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) first
sub-ningePlayer-all: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) all
sub-ningePlayer-clean: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) clean
sub-ningePlayer-distclean: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ningePlayer-install_subtargets: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) install
sub-ningePlayer-uninstall_subtargets: ningePlayer//$(MAKEFILE) FORCE
	cd ningePlayer/ && $(MAKE) -f $(MAKEFILE) uninstall
ningeMain//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ningeMain/ || $(MKDIR) ningeMain/ 
	cd ningeMain/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningeMain/ningeMain.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningeMain-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ningeMain/ || $(MKDIR) ningeMain/ 
	cd ningeMain/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningeMain/ningeMain.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningeMain: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE)
sub-ningeMain-make_default: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) 
sub-ningeMain-make_first: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) first
sub-ningeMain-all: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) all
sub-ningeMain-clean: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) clean
sub-ningeMain-distclean: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ningeMain-install_subtargets: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) install
sub-ningeMain-uninstall_subtargets: ningeMain//$(MAKEFILE) FORCE
	cd ningeMain/ && $(MAKE) -f $(MAKEFILE) uninstall
ningeGal//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ningeGal/ || $(MKDIR) ningeGal/ 
	cd ningeGal/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningeGal/ningeGal.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningeGal-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ningeGal/ || $(MKDIR) ningeGal/ 
	cd ningeGal/ && $(QMAKE) /home/ninsun/ningeproject-ninge/ningeGal/ningeGal.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-ningeGal: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE)
sub-ningeGal-make_default: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) 
sub-ningeGal-make_first: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) first
sub-ningeGal-all: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) all
sub-ningeGal-clean: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) clean
sub-ningeGal-distclean: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ningeGal-install_subtargets: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) install
sub-ningeGal-uninstall_subtargets: ningeGal//$(MAKEFILE) FORCE
	cd ningeGal/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: ningeProject.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ningeProject.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ningeProject.pro

qmake_all: sub-core-qmake_all sub-ninge-qmake_all sub-ningePlayer-qmake_all sub-ningeMain-qmake_all sub-ningeGal-qmake_all FORCE

make_default: sub-core-make_default sub-ninge-make_default sub-ningePlayer-make_default sub-ningeMain-make_default sub-ningeGal-make_default FORCE
make_first: sub-core-make_first sub-ninge-make_first sub-ningePlayer-make_first sub-ningeMain-make_first sub-ningeGal-make_first FORCE
all: sub-core-all sub-ninge-all sub-ningePlayer-all sub-ningeMain-all sub-ningeGal-all FORCE
clean: sub-core-clean sub-ninge-clean sub-ningePlayer-clean sub-ningeMain-clean sub-ningeGal-clean FORCE
distclean: sub-core-distclean sub-ninge-distclean sub-ningePlayer-distclean sub-ningeMain-distclean sub-ningeGal-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-core-install_subtargets sub-ninge-install_subtargets sub-ningePlayer-install_subtargets sub-ningeMain-install_subtargets sub-ningeGal-install_subtargets FORCE
uninstall_subtargets: sub-core-uninstall_subtargets sub-ninge-uninstall_subtargets sub-ningePlayer-uninstall_subtargets sub-ningeMain-uninstall_subtargets sub-ningeGal-uninstall_subtargets FORCE

sub-core-check: core/$(MAKEFILE)
	cd core/ && $(MAKE) check
sub-ninge-check: ninge/$(MAKEFILE)
	cd ninge/ && $(MAKE) check
sub-ningePlayer-check: ningePlayer/$(MAKEFILE)
	cd ningePlayer/ && $(MAKE) check
sub-ningeMain-check: ningeMain/$(MAKEFILE)
	cd ningeMain/ && $(MAKE) check
sub-ningeGal-check: ningeGal/$(MAKEFILE)
	cd ningeGal/ && $(MAKE) check
check: sub-core-check sub-ninge-check sub-ningePlayer-check sub-ningeMain-check sub-ningeGal-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

